 name: Build All Docker container (dry run)

 on:
    pull_request:
    workflow_dispatch:

 jobs:
   build-docker-debian:
     runs-on: ubuntu-latest

     steps:
        - uses: actions/checkout@v4
        - name: Build the debian12 Docker image
          working-directory: ./Debian12
          run: |
           docker build . --file Dockerfile --tag ikarusproject/debian12:latest --build-arg debianversion="bookworm"
           docker build . --file Dockerfile --tag ikarusproject/debian13:latest --build-arg debianversion="trixie"
  
        - name: Build the dunebase Docker image
          working-directory: ./DuneBase
          run: |
           docker build . --file Dockerfile --tag ikarusproject/dunebase-gcc-debian12:latest --build-arg debianversion="12" --build-arg ccompiler="gcc-12" --build-arg cppcompiler="g++-12"
           docker build . --file Dockerfile --tag ikarusproject/dunebase-clang-debian12:latest --build-arg debianversion="12" --build-arg ccompiler="clang-16" --build-arg cppcompiler="clang++-16"
           docker build . --file Dockerfile --tag ikarusproject/dunebase-gcc-debian13:latest --build-arg debianversion="13" --build-arg ccompiler="gcc-14" --build-arg cppcompiler="g++-14"
           docker build . --file Dockerfile --tag ikarusproject/dunebase-clang-debian13:latest --build-arg debianversion="13" --build-arg ccompiler="clang-17" --build-arg cppcompiler="clang++-17"

        - name: Build the Development Docker image
          working-directory: ./DevelopContainer
          run: |
           docker build . --file Dockerfile --tag ikarusproject/ikarus-dev-gcc-debian12:latest --build-arg compiler="gcc-debian12" --build-arg ccompiler="gcc-12" --build-arg cppcompiler="g++-12"
           docker build . --file Dockerfile --tag ikarusproject/ikarus-dev-clang-debian12:latest --build-arg compiler="clang-debian12" --build-arg ccompiler="clang-16" --build-arg cppcompiler="clang++-16"
           docker build . --file Dockerfile --tag ikarusproject/ikarus-dev-gcc-debian13:latest --build-arg compiler="gcc-debian13" --build-arg ccompiler="gcc-14" --build-arg cppcompiler="g++-14"
           docker build . --file Dockerfile --tag ikarusproject/ikarus-dev-clang-debian13:latest --build-arg compiler="clang-debian13" --build-arg ccompiler="clang-17" --build-arg cppcompiler="clang++-17"
        - name: Build the Installed Docker image
          working-directory: ./InstalledContainer
          run: |
           docker build . --file Dockerfile --tag ikarusproject/ikarus-gcc-debian12:latest --build-arg compiler="gcc-debian12" --build-arg ccompiler="gcc-12" --build-arg cppcompiler="g++-12"
           docker build . --file Dockerfile --tag ikarusproject/ikarus-clang-debian12:latest --build-arg compiler="clang-debian12" --build-arg ccompiler="clang-16" --build-arg cppcompiler="clang++-16"
           docker build . --file Dockerfile --tag ikarusproject/ikarus-gcc-debian13:latest --build-arg compiler="gcc-debian13" --build-arg ccompiler="gcc-14" --build-arg cppcompiler="g++-14"
           docker build . --file Dockerfile --tag ikarusproject/ikarus-clang-debian13:latest --build-arg compiler="clang-debian13" --build-arg ccompiler="clang-17" --build-arg cppcompiler="clang++-17"
