name: Build All Docker Containers (dry run)

on:
  push:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        debian_version: [12, 13]
        compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v4

      - name: Set compiler versions
        id: vars
        run: |
          if [[ "${{ matrix.compiler }}" == "gcc" && "${{ matrix.debian_version }}" == "12" ]]; then
            echo "C_COMPILER=gcc-12" >> $GITHUB_ENV
            echo "CPP_COMPILER=g++-12" >> $GITHUB_ENV
          elif [[ "${{ matrix.compiler }}" == "clang" && "${{ matrix.debian_version }}" == "12" ]]; then
            echo "C_COMPILER=clang-16" >> $GITHUB_ENV
            echo "CPP_COMPILER=clang++-16" >> $GITHUB_ENV
          elif [[ "${{ matrix.compiler }}" == "gcc" && "${{ matrix.debian_version }}" == "13" ]]; then
            echo "C_COMPILER=gcc-14" >> $GITHUB_ENV
            echo "CPP_COMPILER=g++-14" >> $GITHUB_ENV
          elif [[ "${{ matrix.compiler }}" == "clang" && "${{ matrix.debian_version }}" == "13" ]]; then
            echo "C_COMPILER=clang-17" >> $GITHUB_ENV
            echo "CPP_COMPILER=clang++-17" >> $GITHUB_ENV
          fi

      - name: Build Debian base image
        working-directory: ./Debian12
        run: |
          if [[ "${{ matrix.debian_version }}" == "12" ]]; then
            docker build . --file Dockerfile --tag ikarusproject/debian12:latest --build-arg debianversion="bookworm"
          else
            docker build . --file Dockerfile --tag ikarusproject/debian13:latest --build-arg debianversion="trixie"
          fi

      - name: Build DuneBase image
        working-directory: ./DuneBase
        run: |
          docker build . --file Dockerfile \
            --tag ikarusproject/dunebase-${{ matrix.compiler }}-debian${{ matrix.debian_version }}:latest \
            --build-arg debianversion="${{ matrix.debian_version }}" \
            --build-arg ccompiler="${{ env.C_COMPILER }}" \
            --build-arg cppcompiler="${{ env.CPP_COMPILER }}"

      - name: Build Develop image
        working-directory: ./DevelopContainer
        run: |
          docker build . --file Dockerfile \
            --tag ikarusproject/ikarus-dev-${{ matrix.compiler }}-debian${{ matrix.debian_version }}:latest \
            --build-arg compiler="${{ matrix.compiler }}-debian${{ matrix.debian_version }}" \
            --build-arg ccompiler="${{ env.C_COMPILER }}" \
            --build-arg cppcompiler="${{ env.CPP_COMPILER }}"

      - name: Build Installed image
        working-directory: ./InstalledContainer
        run: |
          docker build . --file Dockerfile \
            --tag ikarusproject/ikarus-${{ matrix.compiler }}-debian${{ matrix.debian_version }}:latest \
            --build-arg compiler="${{ matrix.compiler }}-debian${{ matrix.debian_version }}" \
            --build-arg ccompiler="${{ env.C_COMPILER }}" \
            --build-arg cppcompiler="${{ env.CPP_COMPILER }}"
